version: 2
jobs:
  build:
    
    working_directory: ~/springboot_swagger_example-master-cassandra

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: springboot_swagger_example-master-cassandra-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: springboot_swagger_example-master-cassandra-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - run:
          name: Setup Heroku
          command: |
            chmod +x .circleci/setup-heroku.sh
            .circleci/setup-heroku.sh
      - run:
          name: Deploy to Heroku
          command: |
            mkdir app
            cd app/
            heroku create 
            git push heroku master
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/spring-boot-web-0.0.1-SNAPSHOT.jar

