version: 2
jobs:
  build:
    
    working_directory: ~/springboot_swagger_example-master-cassandra

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: springboot_swagger_example-master-cassandra-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: springboot_swagger_example-master-cassandra-{{ checksum "pom.xml" }}
          
      - type: add-ssh-keys
      - type: deploy
        name: "Deploy to Heroku"
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            # Install Heroku fingerprint (this is heroku's own key, NOT any of your private or public keys)
            echo 'heroku.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAu8erSx6jh+8ztsfHwkNeFr/SZaSOcvoa8AyMpaerGIPZDB2TKNgNkMSYTLYGDK2ivsqXopo2W7dpQRBIVF80q9mNXy5tbt1WE04gbOBB26Wn2hF4bk3Tu+BNMFbvMjPbkVlC2hcFuQJdH4T2i/dtauyTpJbD/6ExHR9XYVhdhdMs0JsjP/Q5FNoWh2ff9YbZVpDQSTPvusUp4liLjPfa/i0t+2LpNCeWy8Y+V9gUlDWiyYwrfMVI0UwNCZZKHs1Unpc11/4HLitQRtvuk0Ot5qwwBxbmtvCDKZvj1aFBid71/mYdGRPYZMIxq1zgP1acePC1zfTG/lvuQ7d0Pe0kaw==' >> ~/.ssh/known_hosts

            # git push git@heroku.com:yourproject.git $CIRCLE_SHA1:refs/heads/master

            # Optional post-deploy commands
            # heroku run python manage.py migrate --app=my-heroku-project
          fi          
                
      - run: mvn package
      
      - run:
          name: Setup Heroku
          command: |
            curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
            chmod +x .circleci/setup-heroku.sh
            .circleci/setup-heroku.sh
      - run:
          name: Deploy to Heroku
          command: |
            mkdir app
            cd app/ 
            heroku create 
            git push heroku master
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/spring-boot-web-0.0.1-SNAPSHOT.jar

