apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-web-demo
  labels:
    purpose: demonstrate-spring-boot-web
spec:
    containers:
    - name: spring-boot-web
      image: docker.io/joethecoder2/spring-boot-web-0.0.1
      env:
      - name: cassandra_ip
        value: "127.0.0.1"
      - name: cassandra_port
        value: "9042"
      - name: login
        value: "cassandra"
      - name: password
        value: "GN1aJxMnsWOR"
      command: ["/bin/sh","-c", "java -jar spring-boot-web-0.0.1-SNAPSHOT.jar cassandra_ip=$cassandra_ip cassandra_port=$cassandra_port login=$login password=$password"]
    restartPolicy: OnFailure
