# https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/

# https://stackoverflow.com/questions/46425997/kubernetes-create-multiple-pods-deployments-of-the-same-image-with-different-com

apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-web-demo
  labels:
    purpose: demonstrate-spring-boot-web
spec:
  containers:
  - name: spring-boot-web
    image: docker.io/joethecoder2/spring-boot-web
    env:
    - name: cassandra_ip
      value: "127.0.0.1"
    - name: cassandra_port
      value: "9042"
    command: ["java","-jar", "spring-boot-web-0.0.1-SNAPSHOT.jar", "cassandra_ip=127.0.0.1", "cassandra_port=9042"]
    args: ["cassandra_ip=127.0.0.1", "cassandra_port=9042"]
  restartPolicy: OnFailure